/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2020-05-02 11:37:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import sun.java2d.pipe.SpanShapeRenderer.Simple;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

int number = 1;
String str; 
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("sun.java2d.pipe.SpanShapeRenderer.Simple");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>齐心抗疫，共克时艰——陆玺文</title>\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"css/index.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\t您是第");
      out.print(number++);
      out.write("位访问本站的同学!\r\n");
      out.write("\t");
      Bean.info simple = null;
      synchronized (session) {
        simple = (Bean.info) _jspx_page_context.getAttribute("simple", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (simple == null){
          simple = new Bean.info();
          _jspx_page_context.setAttribute("simple", simple, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
str=simple.getID(); 
      out.write('\r');
      out.write('\n');
      out.write('	');
if(str!=null){out.print("欢迎您,"+ str+","); 
      out.write("\r\n");
      out.write("\t<a href=\"jsp/exitLogin.jsp\">注销 </a>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t<div class=\"y\">\r\n");
      out.write("\t\t<span><a href=\"html/login.html\">登录 </a></span>\r\n");
      out.write("\t\t&emsp;\r\n");
      out.write("\t\t<span><a href=\"jsp/zhuce.jsp\">注册 </a></span>\r\n");
      out.write("\t\t&emsp;\r\n");
      out.write("\t\t<span><a href=\"http://www.cumt.edu.cn/fyfkw/\">矿大抗疫</a></span>\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>\r\n");
      out.write("\t\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("\t齐心抗疫，共克时艰！\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 代码 开始 -->\r\n");
      out.write("<!--UL标签class属性必需，图片alt属性值即标题文字-->\r\n");
      out.write("<div class=\"yx-rotaion\">\r\n");
      out.write("\t<ul class=\"rotaion_list\">\r\n");
      out.write("\t\t<li><a href=\"#\"><img src=\"images/img1.jpg\" alt=\"多地医生联手抢救新冠肺炎患者\"></a></li>\r\n");
      out.write("\t\t<li><a href=\"#\"><img src=\"images/img2.jpg\" alt=\"中国向希腊援助抗疫物资\"></a></li>\r\n");
      out.write("\t\t<li><a href=\"#\"><img src=\"images/img3.jpg\" alt='疫情下的纽约'></a></li>\r\n");
      out.write("\t\t<li><a href=\"#\"><img src=\"images/img4.jpg\" alt=\"英国宣布关闭餐饮娱乐场所\"></a></li>\r\n");
      out.write("\t\t<li><a href=\"#\"><img src=\"images/img5.jpg\" alt=\"约旦开始执行强制隔离\"></a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.yx_rotaion.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(\".yx-rotaion\").yx_rotaion({auto:true});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 代码 结束 -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"xinwen_left z\">\r\n");
      out.write("\t<div class=\"tit\">\r\n");
      out.write("\t\t央视快评\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"fenlan\"></div>\r\n");
      out.write("\t<div style=\"font-family: STFangsong;\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t<li><a href=\"http://www.xinhuanet.com/politics/xxjxs/2020-03/22/c_1125749013.htm\" target=\"_blank\" class=\"a3\" >这场硬仗 习近平\"再动员、再部署\"</a></li>\r\n");
      out.write("\t<li><a href=\"http://www.xinhuanet.com/politics/xxjxs/2020-03/20/c_1125744281.htm\" target=\"_blank\" >这个\"重中之重\" 习近平频频提及</a></li>\r\n");
      out.write("\t<li><a href=\"https://wap.peopleapp.com/article/5301017/5208441\" target=\"_blank\" class=\"a3\" >世界卫生组织总干事:武汉零新增病例给世界以希望</a></li>\r\n");
      out.write("\t<li><a href=\"http://m.news.cctv.com/2020/03/22/ARTIMUDquNaPlipJtixdf9UG200322.shtml\" target=\"_blank\"  >中国专家医疗队受最高礼遇迎接 塞总统亲吻五星红旗</a></li>\r\n");
      out.write("\t<li><a href=\"https://wap.peopleapp.com/article/rmh12283261/rmh12283261\" target=\"_blank\" class=\"a3\" >新冠肺炎康复者血浆捐献突破1000人次</a></li>\r\n");
      out.write("\t<li><a href=\"http://www.cssn.cn/zx/bwyc/202003/t20200321_5104156.shtml\" target=\"_blank\" >抗疫故事助力思政课与新时代同频共振</a></li>\r\n");
      out.write("\t<li><a href=\"https://mp.weixin.qq.com/s/nQHCMbuyIfinUf1JRXBigw\" target=\"_blank\" >经济恢复元气</a></li>\r\n");
      out.write("\t<li><a href=\"http://baijiahao.baidu.com/s?id=1661828727271120906\"  target=\"_blank\">全国金融系统1137人感染新冠肺炎，42人不幸去世</a></li>\r\n");
      out.write("\t<li><a href=\"https://3w.huanqiu.com/a/c36dc8/3xWSWKcXH60?agt=8\"  target=\"_blank\">近50国宣布进入紧急状态 部分国家称\"战时状态\"</a></li>\r\n");
      out.write("\t<li><a href=\"http://baijiahao.baidu.com/s?id=1661819897188254447\" target=\"_blank\">特朗普告诉医务人员:口罩可重复使用别扔 有很好的液体消毒</a></li>\r\n");
      out.write("\t<li><a href=\"http://baijiahao.baidu.com/s?id=1661837746956735170\"  target=\"_blank\">对所有欧洲入境者进行新冠病毒检测</a></li>\r\n");
      out.write("\t\t<li><a href=\"http://baijiahao.baidu.com/s?id=1661831680261628302\" target=\"_blank\">央行副行长：目前断定全球进入金融危机还为时尚早</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"xinwen_right z\">\r\n");
      out.write("\t<div class=\"tit\">\r\n");
      out.write("\t\t新闻速递\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"fenlan\"></div>\r\n");
      out.write("\t<div style=\"font-family: STFangsong;\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t<li><a href=\"https://m.chinanews.com/wap/detail/zwsp/sh/2020/03-21/9132911.shtml?from=singlemessage\"  target=\"_blank\">火神山雷神山医院滞汉参建工人将陆续返乡返岗</a></li>\r\n");
      out.write("\t<li><a href=\"http://sn.people.com.cn/GB/n2/2020/0322/c378296-33894250.html\" target=\"_blank\">特警坚守一线 护卫生命通道</a></li>\r\n");
      out.write("\t<li><a href=\"http://news.gmw.cn/2020-03/22/content_33671951.htm\" target=\"_blank\">湖北武汉：多个长江大保护项目开工</a></li>\r\n");
      out.write("\t<li><a href=\"http://m.news.cctv.com/2020/03/21/ARTIKGzWX3HXeGLwlvc3a48r200321.shtml\" target=\"_blank\">独家画面！记者跟拍火神山血浆输注治疗全过程……</a></li>\r\n");
      out.write("\t<li><a href=\"http://news.gmw.cn/2020-03/22/content_33672005.htm\" target=\"_blank\">首个治疗新冠肺炎的中药获临床批件</a><li>\r\n");
      out.write("\t<li><a href=\"http://tv.cctv.com/2020/03/21/VIDEbnyjZt8ucqJylEdAj4pY200321.shtml\" target=\"_blank\">张恩莉：争分夺秒 只为更多患者康复</a></li>\r\n");
      out.write("\t<li><a href=\"http://news.gmw.cn/2020-03/22/content_33672066.htm\"  target=\"_blank\">病毒与人类长期共存 疾控体系是防御长城</a></li>\r\n");
      out.write("\t<li><a href=\"https://xhpfmapi.zhongguowangshi.com/vh512/share/8976516\"  target=\"_blank\">办法总比困难多——首都复工复产一线见闻</a></li>\r\n");
      out.write("\t<li><a href=\"https://3w.huanqiu.com/a/016cda/3xWSnJVILZE?agt=8\"  target=\"_blank\">香港国际机场暂停前往内地的转乘交通接驳服务</a></li>\r\n");
      out.write("\t<li><a href=\"https://3w.huanqiu.com/a/f0d525/9CaKrnKq2Nw?agt=8\" target=\"_blank\">澳总理：美国是澳感染病例的最大来源 抗疫举措步步升级</a></li>\r\n");
      out.write("\t<li><a href=\"https://3w.huanqiu.com/a/c36dc8/3xW4eXGyqHZ?agt=8\" target=\"_blank\">意大利累计确诊超过5万例</a></li>\r\n");
      out.write("\t<li><a href=\"https://baijiahao.baidu.com/s?id=1661816248889795297\" target=\"_blank\">全国停止非必要生产活动</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"xinwen_down z\">\r\n");
      out.write("\t<div class=\"tit\">\r\n");
      out.write("\t\t更多新闻\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"fenlan\"></div>\r\n");
      out.write("\t<div style=\"font-family: STFangsong;\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t<li><a href=\"https://3w.huanqiu.com/a/24d596/3xWQeluxth0?agt=8\" target=\"_blank\">新加坡禁止所有外国人入境或过境</a></li>\r\n");
      out.write("\t<li><a href=\"http://m.top.cnr.cn/bdxw/20200322/t20200322_525025218.html\" target=\"_blank\">湖北记者披露武汉新增100多例?官方辟谣:新增为0</a></li>\r\n");
      out.write("\t<li><a href=\"https://3w.huanqiu.com/a/2928e7/3xWJnY57sm8?agt=8\"  target=\"_blank\">卫健委:新增确诊46例 其中境外输入病例45例 湖北4日无新增</a></li>\r\n");
      out.write("\t<li><a href=\"https://3w.huanqiu.com/a/423dc4/3xWUYvWlkKp?agt=8\"  target=\"_blank\">民航局:目的地为北京的国际航班需从指定入境点入境</a></li>\r\n");
      out.write("\t<li><a href=\"http://baijiahao.baidu.com/s?id=1661840695780543331\"  target=\"_blank\">北京新增境外输入确诊病例2例 为英国输入病例</a></li>\r\n");
      out.write("\t<li><a href=\"http://baijiahao.baidu.com/s?id=1661836604896653131\"  target=\"_blank\">湖北：新冠肺炎确诊贫困人口每人获补助1万元</a></li>\r\n");
      out.write("\t<li><a href=\"https://3w.huanqiu.com/a/4dbeda/9CaKrnKq32y?agt=8\" target=\"_blank\">张文宏：疫情夏天会经历低谷 冬天是否复发不好说</a></li>\r\n");
      out.write("\t<li><a href=\"https://3w.huanqiu.com/a/cfb23b/3xWTSjq0xiI?agt=8\"  target=\"_blank\">境外输入关联病例是啥？广州的解释来了</a></li>\r\n");
      out.write("\t<li><a href=\"https://3w.huanqiu.com/a/0c789f/3xWWLFQ7GWL?agt=8\" target=\"_blank\">上海市卫健委：上海对非重点国家所有入境人员核酸检测</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("\t制作：陆玺文&emsp;计科6班&emsp;03170908&ensp;.\r\n");
      out.write("</footer>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
